package uikit

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.material3.ColorScheme as M3ColorScheme
import androidx.compose.material3.lightColorScheme as m3LightColorScheme
import androidx.compose.material3.darkColorScheme as m3DarkColorScheme

internal val LocalColorScheme = staticCompositionLocalOf { lightColorScheme() }

internal fun lightColorScheme(): ColorScheme = ColorScheme(
    primary = Color(0xFF9000D4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF3D9FF),
    onPrimaryContainer = Color(0xFF21003D),
    inversePrimary = Color(0xFFDFAEFF),
    secondary = Color(0xFF5C5C5C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1A1A1A),
    tertiary = Color(0xFF6D009F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFAEFFF),
    onTertiaryContainer = Color(0xFF21003D),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFAFAFA),
    onBackground = Color(0xFF1A1A1A),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF1A1A1A),
    surfaceVariant = Color(0xFFF3F3F3),
    onSurfaceVariant = Color(0xFF4A4458),
    surfaceTint = Color(0xFF9000D4),
    inverseSurface = Color(0xFF2E2E2E),
    inverseOnSurface = Color(0xFFE8E8E8),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE8E8E8),
    surfaceContainer = Color(0xFFF3F3F3),
    surfaceContainerHigh = Color(0xFFECECEC),
    surfaceContainerHighest = Color(0xFFE5E5E5),
    surfaceContainerLow = Color(0xFFF7F7F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    outline = Color(0xFF7A7289),
    outlineVariant = Color(0xFFCBC2DB),
    scrim = Color(0xFF000000),
    // Кастомные цвета для событий
    eventOnline = Color(0xFF1DC0A6),
    eventOffline = Color(0xFF5A6A8E),
    eventFinished = Color(0xFFCCCCCC),
    tagBackground = Color(0xFFF3D9FF),
    tagContent = Color(0xFF9000D4),
)

internal fun darkColorScheme(): ColorScheme = ColorScheme(
    primary = Color(0xFFDFAEFF),
    onPrimary = Color(0xFF4B006E),
    primaryContainer = Color(0xFF6D009F),
    onPrimaryContainer = Color(0xFFF3D9FF),
    inversePrimary = Color(0xFF9000D4),
    secondary = Color(0xFFCBC2DB),
    onSecondary = Color(0xFF2E2E2E),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DEF8),
    tertiary = Color(0xFFBE5FFF),
    onTertiary = Color(0xFF21003D),
    tertiaryContainer = Color(0xFF4B006E),
    onTertiaryContainer = Color(0xFFF3D9FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF410002),
    errorContainer = Color(0xFFBA1A1A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1A1A),
    onBackground = Color(0xFFE8E8E8),
    surface = Color(0xFF2E2E2E),
    onSurface = Color(0xFFE8E8E8),
    surfaceVariant = Color(0xFF4A4458),
    onSurfaceVariant = Color(0xFFCBC2DB),
    surfaceTint = Color(0xFFDFAEFF),
    inverseSurface = Color(0xFFE8E8E8),
    inverseOnSurface = Color(0xFF2E2E2E),
    surfaceBright = Color(0xFF4A4458),
    surfaceDim = Color(0xFF1A1A1A),
    surfaceContainer = Color(0xFF2E2E2E),
    surfaceContainerHigh = Color(0xFF383838),
    surfaceContainerHighest = Color(0xFF444444),
    surfaceContainerLow = Color(0xFF242424),
    surfaceContainerLowest = Color(0xFF1A1A1A),
    outline = Color(0xFF7A7289),
    outlineVariant = Color(0xFF4A4458),
    scrim = Color(0xFF000000),
    // Кастомные цвета для событий
    eventOnline = Color(0xFF1DC0A6),
    eventOffline = Color(0xFF8B9BB4),
    eventFinished = Color(0xFF5C5C5C),
    tagBackground = Color(0xFF4B006E),
    tagContent = Color(0xFFDFAEFF),
)

@Immutable
data class ColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerLowest: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    // Кастомные — специфичные для Meetings
    val eventOnline: Color,
    val eventOffline: Color,
    val eventFinished: Color,
    val tagBackground: Color,
    val tagContent: Color,
)

internal fun ColorScheme.toM3ColorScheme(isDark: Boolean = false): M3ColorScheme {
    val base = if (isDark) m3DarkColorScheme() else m3LightColorScheme()
    return base.copy(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surfaceBright,
        surfaceDim = surfaceDim,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
        surfaceContainerLow = surfaceContainerLow,
        surfaceContainerLowest = surfaceContainerLowest,
    )
}