name: Code Quality Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check build
      run: ./gradlew :ktlintCheck :detekt :meetings-android:lintDebug --continue

    - name: Save KtLint Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ktlint-report
        path: build/reports/ktlint/

    - name: Save Detekt Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: detekt-report
        path: build/reports/detekt

    - name: Save Android Lint Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-lint-report
        path: meetings-android/build/reports/lint-results-debug.html

    - name: Save Gradle Problems Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-problems-report
        path: build/reports/problems
